@startuml A Newsserver Implementation

actor user

participant newsclient
participant connection
participant MessageHandler
participant connectionclosedexception
participant Protocol 
participant server
participant newsserver

database Database
database InMemDatabase
database FileDatabase 


user -> newsclient: Something

newsclient -> connection: X
newsclient -> MessageHandler
newsclient -> connectionclosedexception
newsclient -> Protocol
newsclient -> newsserver: something

MessageHandler -> connection
MessageHandler -> connectionclosedexception
MessageHandler -> Protocol

newsserver -> connection
newsserver -> MessageHandler
newsserver -> connectionclosedexception
newsserver -> Protocol
newsserver -> server
newsserver -> Database

Database -> InMemDatabase
Database -> FileDatabase

server -> connection

@enduml